### PR TITLE
Feat/blindsign flow

### PR DESCRIPTION
**Pull request by chcmedeiros**

### CODE REVIEW

**Comment by emmanuelm41** [comment]
I think there is a typo on the blind signing message on nano s. I think it should be "could loose" instead of "could lose"

**Comment by emmanuelm41** [comment]
Same happens for nano s and x

**Review by emmanuelm41 — CHANGES_REQUESTED** [review]
Review my previous messages

**Comment by chcmedeiros** [comment]
> Review my previous messages

I think we need 'lose' since funds might be lost in the transaction.

**Review by emmanuelm41 — APPROVED** [review]

**Pull request merged**
